import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { MoreThanOrEqual, type Repository } from "typeorm";
import type {
  CreateSupportMessageInput,
  ListSupportTicketsFilters,
  SupportMessageRepositoryPort,
  SupportTicketView,
} from "@/modules/support/application/ports/support-message-repository.port";
import { SupportTicketStatus } from "@/modules/support/domain/support.enums";
import { SupportMessageOrmEntity } from "@/modules/support/infrastructure/persistence/typeorm/entities/support-message.orm-entity";
import { paginate, type Paginated } from "@/shared/application/pagination";

@Injectable()
export class SupportMessageTypeormRepository implements SupportMessageRepositoryPort {
  constructor(
    @InjectRepository(SupportMessageOrmEntity)
    private readonly repository: Repository<SupportMessageOrmEntity>,
  ) {}

  async create(input: CreateSupportMessageInput): Promise<SupportTicketView> {
    const saved = await this.repository.save(
      this.repository.create({ ...input, status: SupportTicketStatus.OPEN }),
    );
    // Re-read: the protocol number is generated by the database.
    return this.mustFind(saved.id);
  }

  hasMessageSince(userId: string, since: Date): Promise<boolean> {
    return this.repository.existsBy({
      userId,
      createdAt: MoreThanOrEqual(since),
    });
  }

  async findById(id: string): Promise<SupportTicketView | null> {
    const row = await this.repository.findOneBy({ id });
    return row ? toView(row) : null;
  }

  countByStatus(status: SupportTicketStatus): Promise<number> {
    return this.repository.countBy({ status });
  }

  async list(
    filters: ListSupportTicketsFilters,
  ): Promise<Paginated<SupportTicketView>> {
    const [rows, total] = await this.repository.findAndCount({
      where: {
        ...(filters.status ? { status: filters.status } : {}),
        ...(filters.category ? { category: filters.category } : {}),
      },
      order: { createdAt: "DESC" },
      skip: (filters.page - 1) * filters.limit,
      take: filters.limit,
    });
    return paginate(rows.map(toView), total, filters);
  }

  async reply(
    id: string,
    reply: { adminReply: string; repliedAt: Date; repliedByAdminId: string },
  ): Promise<SupportTicketView> {
    await this.repository.update(
      { id },
      { ...reply, status: SupportTicketStatus.ANSWERED },
    );
    return this.mustFind(id);
  }

  async finalize(
    id: string,
    finalization: { finalizedAt: Date; finalizedByAdminId: string },
  ): Promise<SupportTicketView> {
    await this.repository.update(
      { id },
      { ...finalization, status: SupportTicketStatus.RESOLVED },
    );
    return this.mustFind(id);
  }

  private async mustFind(id: string): Promise<SupportTicketView> {
    return toView(await this.repository.findOneByOrFail({ id }));
  }
}

function toView(row: SupportMessageOrmEntity): SupportTicketView {
  return {
    id: row.id,
    userId: row.userId,
    protocolNumber: row.protocolNumber,
    category: row.category,
    message: row.message,
    status: row.status,
    adminReply: row.adminReply ?? null,
    repliedAt: row.repliedAt ?? null,
    repliedByAdminId: row.repliedByAdminId ?? null,
    finalizedAt: row.finalizedAt ?? null,
    finalizedByAdminId: row.finalizedByAdminId ?? null,
    createdAt: row.createdAt,
  };
}
